[package]
name = "cube-query"
version = "0.1.3"
edition = "2021"
description = "A tool for querying the CubeMX database"
license = "MIT"
authors = ["Andrew Gazelka <andrew.gazelka@gmail.com>"]

[dependencies]
cube-query-lib = { path = "../cube-query-lib", version = "0.1.0" }